workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - cd ios && pod install && cd ..
      - flutter build ipa --release